CREATE SCHEMA DBATK

CREATE TABLE DBATK.tb_users (
    cd_user INT PRIMARY KEY,
    nm_user VARCHAR(100) NOT NULL,
    ds_email VARCHAR(150) NOT NULL UNIQUE,
    dt_created DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE DBATK.tb_tasks (
	cd_task INT PRIMARY KEY,
	nm_title VARCHAR(60) NOT NULL,
	ds_task VARCHAR(300) NOT NULL,
	tp_status CHAR(1) NOT NULL DEFAULT 'P',
	dt_created DATE NOT NULL DEFAULT CURRENT_DATE,
	dt_limit DATE,
	cd_user INT NOT NULL,
	FOREIGN KEY (cd_user) REFERENCES DBATK.tb_users (cd_user),
	CONSTRAINT chk_tp_status CHECK (tp_status IN ('P', 'C', 'A'))
);

CREATE SEQUENCE DBATK.seq_user
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  NO MAXVALUE
  CACHE 1;

CREATE SEQUENCE DBATK.seq_task
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  NO MAXVALUE
  CACHE 1;